# Generated by Django 2.1.1 on 2018-09-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction_course_model', '0002_direction_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='course_id',
        ),
    ]
