# Generated by Django 2.1.1 on 2018-09-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_model', '0004_auto_20180928_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='saved_lessons',
            new_name='saved_lesson',
        ),
    ]
