# Generated by Django 2.1.1 on 2018-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_student_model', '0001_initial'),
        ('homework_model', '0001_initial'),
        ('like_model', '0001_initial'),
        ('direction_course_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('upcoming_webinar', models.DateTimeField()),
                ('progress', models.IntegerField()),
                ('leave_course', models.BooleanField()),
                ('price', models.IntegerField()),
                ('student_count', models.PositiveIntegerField()),
                ('direction', models.ManyToManyField(to='direction_course_model.Direction')),
                ('home_work', models.ManyToManyField(to='homework_model.HomeWork')),
                ('lesson', models.ManyToManyField(to='test_student_model.Lesson')),
                ('likes', models.ManyToManyField(to='like_model.Like')),
                ('work', models.ManyToManyField(to='test_student_model.Work')),
            ],
        ),
    ]
