# Generated by Django 2.1.1 on 2018-09-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction_course_model', '0001_initial'),
        ('course_model', '0002_auto_20180928_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direction',
        ),
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direction_course_model.Direction'),
        ),
    ]
