# Generated by Django 2.1.1 on 2018-09-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_model', '0003_auto_20180928_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction_course_model.Direction'),
        ),
    ]
