# Generated by Django 2.1.1 on 2018-09-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_model', '0006_auto_20180928_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direction',
        ),
    ]
