# Generated by Django 2.1.1 on 2018-09-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_model', '0007_remove_course_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='likes',
            new_name='like',
        ),
    ]
