# Generated by Django 2.1.1 on 2018-09-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction_course_model', '0003_remove_direction_course_id'),
        ('course_model', '0008_auto_20180928_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction_course_model.Direction'),
        ),
    ]
