# Generated by Django 2.1.1 on 2018-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
