# Generated by Django 2.1.1 on 2018-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
