# Generated by Django 2.1.1 on 2018-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_model', '0002_homework_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
